name: app_test
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^8.0.3
  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  dio: ^5.3.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3+1
  webview_flutter: ^4.2.3
  flutter_inappwebview: ^5.3.2
  carousel_slider: ^4.0.0
  babstrap_settings_screen: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  freezed: ^2.4.2
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Spotify.png
    - assets/images/OneDrive.png
    - assets/images/YouTube.png
    - assets/images/pink.jpg
    - assets/images/gary.jpg
    - assets/images/purple.jpg
    - assets/images/faceID.png
    - assets/images/avatar.png


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
